#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$repo_root"

: "${OWNER:=LoongEnv-HIT}"
: "${MEMBER_REPOS:=LoongEnv-ZHU_YH|ZHU_YH}"

generated_at="$(date -u +"%Y-%m-%d %H:%M UTC")"
tmp_root="$(mktemp -d)"
snapshot_dir="docs/project-snapshots"
snapshot_doc="docs/project-snapshots.md"
trap 'rm -rf "$tmp_root"' EXIT

mkdir -p "$snapshot_dir"
find "$snapshot_dir" -type f -name '*.png' -delete

{
  echo "# Project Snapshots"
  echo
  echo "- Generated by \`DOCS_AI\`"
  echo "- Updated at: ${generated_at}"
  echo
  echo "## Frontend Project Snapshots"
  echo
} > "$snapshot_doc"

found_any=0
port=4300

detect_frontend_dirs() {
  local repo_dir="$1"

  find "$repo_dir" -maxdepth 3 -name package.json -print0 | while IFS= read -r -d '' package_file; do
    local project_dir
    project_dir="$(dirname "$package_file")"

    if jq -e '.scripts.build // .scripts.dev // empty' "$package_file" >/dev/null 2>&1; then
      printf '%s\n' "$project_dir"
      continue
    fi

    if [[ -f "$project_dir/index.html" ]]; then
      printf '%s\n' "$project_dir"
    fi
  done
}

for entry in ${MEMBER_REPOS}; do
  repo="${entry%%|*}"
  label="${entry#*|}"
  if [[ "$label" == "$entry" ]]; then
    label="$repo"
  fi

  clone_dir="$tmp_root/$repo"

  if ! git clone --depth 1 "https://github.com/${OWNER}/${repo}.git" "$clone_dir" >/dev/null 2>&1; then
    {
      echo "### ${label}"
      echo
      echo "- Repository: \`${OWNER}/${repo}\`"
      echo "- Snapshot: repository not available."
      echo
    } >> "$snapshot_doc"
    continue
  fi

  frontend_dirs="$(detect_frontend_dirs "$clone_dir" | sort -u || true)"

  if [[ -z "$frontend_dirs" ]]; then
    {
      echo "### ${label}"
      echo
      echo "- Repository: \`${OWNER}/${repo}\`"
      echo "- Snapshot: no frontend project detected."
      echo
    } >> "$snapshot_doc"
    continue
  fi

  while IFS= read -r project_dir; do
    [[ -z "$project_dir" ]] && continue

    found_any=1
    project_name="$(basename "$project_dir")"
    rel_project_path="${project_dir#"$clone_dir"/}"
    image_name="${label}-${project_name}.png"
    image_rel_path="project-snapshots/${image_name}"
    image_abs_path="$snapshot_dir/${image_name}"
    server_root="$project_dir"

    pushd "$project_dir" >/dev/null
    if [[ -f package-lock.json ]]; then
      npm ci --no-audit --no-fund >/dev/null
    else
      npm install --no-audit --no-fund >/dev/null
    fi

    if jq -e '.scripts.build // empty' package.json >/dev/null 2>&1; then
      npm run build >/dev/null
    fi

    if [[ -d dist ]]; then
      server_root="$project_dir/dist"
    elif [[ -d build ]]; then
      server_root="$project_dir/build"
    fi
    popd >/dev/null

    python3 -m http.server "$port" --bind 127.0.0.1 --directory "$server_root" >"$tmp_root/http-${port}.log" 2>&1 &
    server_pid=$!
    sleep 3

    if npx -y -p playwright@1.52.0 node .github/scripts/capture_screenshot.mjs "http://127.0.0.1:${port}" "$image_abs_path" >/dev/null 2>&1; then
      {
        echo "### ${label} / ${project_name}"
        echo
        echo "- Repository: \`${OWNER}/${repo}\`"
        echo "- Project path: \`${rel_project_path}\`"
        echo
        echo "![${label} ${project_name} homepage snapshot](./${image_rel_path})"
        echo
      } >> "$snapshot_doc"
    else
      {
        echo "### ${label} / ${project_name}"
        echo
        echo "- Repository: \`${OWNER}/${repo}\`"
        echo "- Project path: \`${rel_project_path}\`"
        echo "- Snapshot: capture failed."
        echo
      } >> "$snapshot_doc"
    fi

    kill "$server_pid" >/dev/null 2>&1 || true
    wait "$server_pid" 2>/dev/null || true
    port=$((port + 1))
  done <<< "$frontend_dirs"
done

if [[ "$found_any" -eq 0 ]]; then
  {
    echo "- No frontend projects detected in the current member repositories."
    echo
  } >> "$snapshot_doc"
fi
